# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
      required_providers {
        azurerm = {
          source = "hashicorp/azurerm"
          version = "2.95.0"
        }
      }
    }

    provider "azurerm" {
        features {}
        subscription_id    = "56b988a3-eb59-4d5e-ad42-b22f73ee10f8"
        client_id          = "b57aa9cc-f4c8-45dd-936c-58410a58c32e"
        client_secret      = "1mZ8Q~j5uEZh7BT5surYlte4hDZLKzE-hrFyzcT3"
        tenant_id          = "ba629565-9419-4007-a10f-ec72243a319b"
    }
